//! Stress test: evaluating a large hand-rolled script must complete
//! without panic and without the engine returning
//! [`EvalError::Engine("out of memory")`].
//!
//! Why this test exists
//! --------------------
//!
//! Heso's previous QuickJS heap config (10 MB memory limit, default
//! 256 KB GC threshold) OOM'd during eval of common Next.js /
//! Turbopack chunks on real sites:
//!
//! - stripe.com `_app-…js` (≈ 2.3 MB source)
//! - posthog.com `app-…js` (≈ 7.4 MB source) + secondary chunks
//! - bun.sh `inkeep.min.js` (≈ 5.4 MB source)
//!
//! QuickJS holds the source string, the AST, the generated bytecode,
//! and the closure environments simultaneously while a top-level
//! `<script>` parses + executes, so peak heap is typically 5 – 10×
//! the source. A 10 MB cap couldn't even fit posthog's raw source.
//!
//! This test pins the regression: a 50,000-function bundle (≈ a few
//! MB of source) must eval to completion. If the heap cap regresses
//! below what real-world bundles need, this test catches it without
//! needing live network access to stripe / posthog / bun.

use heso_engine_js::JsEngine;

/// Build a synthetic JS source string that's "heavy" in the same
/// shape real bundles are: many small functions in a single top-level
/// program, plus an array literal of references. The total size
/// pushes well past the old 10 MB memory cap once the parser has
/// expanded it into an AST.
fn synthetic_heavy_bundle(n_functions: usize) -> String {
    // Each function occupies ~110 bytes of source after the `\n` and
    // a non-trivial body so QuickJS actually has to parse + bytecode-
    // compile something, not just trivially fold. The body does a
    // tiny bit of arithmetic so the optimizer can't constant-fold the
    // whole thing into a single integer.
    let mut s = String::with_capacity(n_functions * 128);
    s.push_str("const __heso_fns = [];\n");
    for i in 0..n_functions {
        s.push_str(&format!(
            "function __heso_fn_{i}(a, b) {{ const x = a * {i} + b; \
             return x > 0 ? x + {i} : x - {i}; }}\n\
             __heso_fns.push(__heso_fn_{i});\n",
            i = i
        ));
    }
    // Final expression so we have something concrete to assert on.
    // Sum of the first 100 function results applied to (1, 2) — a
    // small fixed amount of *runtime* work so most of the cost is in
    // parsing + bytecode emission, not in execution.
    s.push_str(
        "let __heso_sum = 0;\n\
         for (let i = 0; i < 100; i++) __heso_sum += __heso_fns[i](1, 2);\n\
         __heso_sum;\n",
    );
    s
}

#[test]
fn heavy_bundle_evaluates_without_oom() {
    // 50,000 functions ≈ 5 – 6 MB of source. Well past the old
    // 10 MB memory cap once the AST + bytecode are resident.
    let bundle = synthetic_heavy_bundle(50_000);
    assert!(
        bundle.len() > 4 * 1024 * 1024,
        "synthetic bundle should be > 4 MB, got {} bytes",
        bundle.len()
    );

    let engine = JsEngine::new().expect("engine::new");
    let outcome = engine
        .eval(&bundle)
        .expect("heavy bundle eval should not OOM under the tuned heap config");

    // Final expression is `__heso_sum`, the sum of __heso_fn_0..99
    // applied to (1, 2). For each i in 0..100: x = 1 * i + 2 = i + 2,
    // which is > 0 for every i, so we return (i + 2) + i = 2i + 2.
    // Sum over i in 0..100: 2 * (0+1+…+99) + 2*100 = 2 * 4950 + 200
    // = 10100.
    assert_eq!(outcome.value, serde_json::Value::from(10_100i64));
}

#[test]
fn many_sequential_bundles_dont_leak_into_oom() {
    // Repeatedly construct a fresh engine + eval a moderately-sized
    // bundle to confirm we're not slowly leaking past the 256 MB cap
    // across engine lifecycles. Each engine drop should release its
    // heap; the test fails if any pass starts returning OOM.
    //
    // We deliberately use a *new* engine per pass rather than
    // re-evaluating on the same one, because `eval` runs in the
    // engine's persistent global scope — a second `const __heso_fns`
    // declaration would throw a redeclaration error orthogonal to
    // what this test pins.
    let bundle = synthetic_heavy_bundle(5_000);
    for pass in 0..10 {
        let engine = JsEngine::new().expect("engine::new");
        let outcome = engine.eval(&bundle).unwrap_or_else(|e| {
            panic!("pass {pass} failed under tuned heap config: {e:?}");
        });
        assert_eq!(
            outcome.value,
            serde_json::Value::from(10_100i64),
            "pass {pass} returned wrong value"
        );
    }
}
